language: go

go:
   - 1.2
   - tip

install:
   - export PATH=$PATH:$HOME/gopath/bin
   - ./build.sh setup
   - go get code.google.com/p/go.tools/cmd/cover
   - go get github.com/mattn/goveralls

script:
   - ./build.sh test-cov

after_success:
   - goveralls -coverprofile=acc.out -service=travis-ci
